#!/usr/bin/env python3
"""
Process one (window, lineage) group: tn93 CSV → EpiLink compatibility weights → Leiden clusters.

Reads:
  --tn93-csv    CSV with ID1, ID2, Distance columns (proportion, not SNP count)
  --seq-ids     Text file: one sequence_id per line (the full group membership)
  --metadata    Parquet (or .obj) with columns: sequence_id index, collection_date

Writes:
  <out-long-dir>/<stem>.parquet  long-format with columns:
    sequence_id, window_id, resolution, cluster_id

Usage:
  python3 method/03_process_group.py \\
      --tn93-csv data/processed/group_fastas/tn93_results/W001_BA.2_124.csv \\
      --seq-ids  data/processed/group_fastas/W001_BA.2_124.ids \\
      --metadata data/processed/scotland_sequence_metadata.parquet \\
      --out-long-dir data/processed/cluster_assignments_long

Typically called in parallel via method/parallel_run.sh with the command file
generated by 04_gen_cluster_commands.py (or directly from the tn93 command file
using a two-step approach).
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import igraph as ig

from epilink_wrapper import estimate_epilink_compatibility


ALIGNMENT_LENGTH_DEFAULT = 29903


def setup_logging(level: str = "INFO") -> None:
    logging.basicConfig(
        level=getattr(logging, level.upper(), logging.INFO),
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def parse_group_label(stem: str) -> tuple[str | None, str | None]:
    m = re.match(r"^(W\d{1,4})_([^_]+)(?:_\d+)?$", stem)
    if m:
        return m.group(1), m.group(2)
    return None, None


def load_metadata_dates(path: Path) -> pd.Series:
    df = pd.read_parquet(path, columns=["sequence_id", "collection_date"])
    df = df.drop_duplicates("sequence_id").set_index("sequence_id")
    ser = pd.to_datetime(df["collection_date"], errors="coerce").dropna()
    return ser


def read_seq_ids(path: Path) -> list[str]:
    with open(path, encoding="utf-8", errors="replace") as f:
        return [ln.strip() for ln in f if ln.strip()]


def fallback_isolates(seq_ids: list[str], resolutions: list[float], window_id: str, lineage: str) -> pd.DataFrame:
    rows = [
        {"sequence_id": sid, "window_id": window_id, "resolution": res,
         "cluster_id": f"{window_id}|{lineage}|R{res}|S{i}"}
        for i, sid in enumerate(sorted(seq_ids), start=1)
        for res in resolutions
    ]
    return pd.DataFrame(rows)


def set_igraph_seed(seed: int) -> None:
    try:
        ig.set_random_number_generator(np.random.default_rng(seed))
    except (AttributeError, TypeError):
        try:
            ig.set_random_number_generator(np.random.RandomState(seed))
        except Exception:
            pass


def process_group(
    tn93_csv: Path,
    seq_ids_path: Path,
    metadata_path: Path,
    out_long_dir: Path,
    alignment_length: int,
    resolutions: list[float],
    seed: int = 42,
    sparsification: float = 1e-4,
) -> Path:
    out_long_dir.mkdir(parents=True, exist_ok=True)
    stem = tn93_csv.stem
    window_id, lineage = parse_group_label(stem)
    out_path = out_long_dir / f"{stem}.parquet"

    date_map = load_metadata_dates(metadata_path)
    group_ids = read_seq_ids(seq_ids_path) if seq_ids_path.exists() else []

    # Load and clean TN93 distances
    df = pd.read_csv(tn93_csv)
    for col in ("ID1", "ID2", "Distance"):
        if col not in df.columns:
            raise ValueError(f"{tn93_csv} missing column '{col}'")

    df = df.dropna(subset=["ID1", "ID2", "Distance"]).copy()
    df["Distance"] = pd.to_numeric(df["Distance"], errors="coerce")
    df = df[df["Distance"].between(0, 1, inclusive="both")]
    df = df[df["ID1"] != df["ID2"]]

    # Deduplicate undirected pairs
    a, b = df["ID1"].astype(str), df["ID2"].astype(str)
    key = pd.DataFrame({"a": np.minimum(a, b), "b": np.maximum(a, b)})
    df = df.loc[~key.duplicated(keep="first")].copy()

    df["snp_distance"] = np.rint(df["Distance"] * alignment_length).astype(float)

    if not group_ids:
        group_ids = pd.unique(pd.concat([df["ID1"], df["ID2"]], ignore_index=True)).tolist()

    # Temporal distances
    df["date1"] = pd.to_datetime(df["ID1"].map(date_map), errors="coerce")
    df["date2"] = pd.to_datetime(df["ID2"].map(date_map), errors="coerce")
    n_missing = df["date1"].isna().sum() + df["date2"].isna().sum()
    if n_missing:
        logging.warning("%s: dropping %d edges with missing dates", stem, n_missing)
    df = df.dropna(subset=["date1", "date2"])
    df["temporal_distance"] = (df["date1"] - df["date2"]).abs().dt.days.astype(float)

    if df.empty:
        result = fallback_isolates(group_ids, resolutions, window_id, lineage)
        result.to_parquet(out_path, index=False, compression="zstd")
        logging.info("%s: no usable edges → %d isolates written", stem, len(group_ids))
        return out_path

    # Epilink compatibility scores (edge weights)
    try:
        df["weight"] = estimate_epilink_compatibility(
            genetic_distance=df["snp_distance"].to_numpy(dtype=float),
            temporal_distance=df["temporal_distance"].to_numpy(dtype=float),
        )
    except Exception as exc:
        logging.warning("%s: epilink failed (%s) → fallback isolates", stem, exc)
        result = fallback_isolates(group_ids, resolutions, window_id, lineage)
        result.to_parquet(out_path, index=False, compression="zstd")
        return out_path

    df = df[df["weight"] > sparsification]
    if df.empty:
        logging.warning("%s: all weights < %g → fallback isolates", stem, sparsification)
        result = fallback_isolates(group_ids, resolutions, window_id, lineage)
        result.to_parquet(out_path, index=False, compression="zstd")
        return out_path

    # Build weighted graph + add isolates
    g = ig.Graph.TupleList(
        df[["ID1", "ID2", "weight"]].to_records(index=False).tolist(),
        directed=False, edge_attrs=["weight"],
    )
    missing_nodes = list(set(group_ids) - set(g.vs["name"]))
    if missing_nodes:
        g.add_vertices(missing_nodes)

    set_igraph_seed(seed)

    # Leiden at each resolution
    rows = []
    for res in resolutions:
        comms = g.community_leiden(weights="weight", resolution=res, n_iterations=10)
        for i, community in enumerate(comms, start=1):
            cid = f"C{i}" if len(community) > 1 else f"S{i}"
            for v_idx in community:
                rows.append({
                    "sequence_id": g.vs[v_idx]["name"],
                    "window_id": window_id,
                    "resolution": res,
                    "cluster_id": f"{window_id}|{lineage}|R{res}|{cid}",
                })

    result = pd.DataFrame(rows).sort_values(
        ["sequence_id", "resolution", "cluster_id"], kind="mergesort"
    )
    result.to_parquet(out_path, index=False, compression="zstd")
    logging.info(
        "%s: %d sequences × %d resolutions → %s",
        stem, result["sequence_id"].nunique(), len(resolutions), out_path.name,
    )
    return out_path


def main() -> int:
    ap = argparse.ArgumentParser(description="Process one tn93 group into Leiden cluster assignments.")
    ap.add_argument("--tn93-csv", type=Path, required=True)
    ap.add_argument("--seq-ids", type=Path, required=True)
    ap.add_argument("--metadata", type=Path, required=True)
    ap.add_argument("--out-long-dir", type=Path, required=True)
    ap.add_argument("--alignment-length", type=int, default=ALIGNMENT_LENGTH_DEFAULT)
    ap.add_argument("--resolutions", type=str, default="0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--sparsification", type=float, default=1e-4)
    ap.add_argument("--log-level", default="INFO")
    args = ap.parse_args()

    setup_logging(args.log_level)
    resolutions = [float(x) for x in args.resolutions.split(",") if x.strip()]

    process_group(
        tn93_csv=args.tn93_csv,
        seq_ids_path=args.seq_ids,
        metadata_path=args.metadata,
        out_long_dir=args.out_long_dir,
        alignment_length=args.alignment_length,
        resolutions=resolutions,
        seed=args.seed,
        sparsification=args.sparsification,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
