"""Cluster one pairwise compatibility parquet with Leiden.

Reads:
    --pairwise-file  Parquet from 03_build_pairwise_dataset.py with id1, id2,
                        and epilink_compatibility columns.
    --seq-ids        Optional text file with the full group membership. When
                        present, nodes with no retained pairwise edges are kept as isolates.

Writes:
    <out-long-dir>/<stem>.parquet  long-format with columns:
    sequence_id, window_id, resolution, cluster_id

Usage:
    python3 method/cluster_pairwise.py \
        --pairwise-file data/processed/pairwise_distances_dataset/W001_B.1_6.parquet \
        --out-long-dir data/processed/cluster_assignments_long

Typically called in parallel via method/parallel_run.sh with the command file
generated by 04_gen_cluster_commands.py.
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
from pathlib import Path
from typing import Any

import igraph as ig
import numpy as np
import pandas as pd


def setup_logging(level: str = "INFO") -> None:
    """Configure timestamped console logging for one pairwise clustering run."""
    logging.basicConfig(
        level=getattr(logging, level.upper(), logging.INFO),
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def normalise_window(value: str) -> str:
    """Return W-prefixed, zero-padded window IDs where possible."""
    value = str(value).strip()
    upper = value.upper()
    if upper.startswith("W") and upper[1:].isdigit():
        return f"W{int(upper[1:]):03d}"
    if upper.isdigit():
        return f"W{int(upper):03d}"
    return value


def parse_pairwise_label(stem: str) -> tuple[str, str, int | None]:
    """Extract window ID, lineage label, and sequence count from a pairwise stem."""
    parts = stem.split("_")
    if len(parts) >= 3 and parts[-1].isdigit():
        return normalise_window(parts[0]), "_".join(parts[1:-1]), int(parts[-1])

    m = re.match(r"^(W\d{1,4})_([^_]+)(?:_\d+)?$", stem)
    if m:
        return normalise_window(m.group(1)), m.group(2), None
    return "", "", None


def read_seq_ids(path: Path) -> list[str]:
    """Read one sequence ID per line from a group membership file."""
    with open(path, encoding="utf-8", errors="replace") as f:
        return [ln.strip() for ln in f if ln.strip()]


def fallback_isolates(
    seq_ids: list[str],
    resolutions: list[float],
    window_id: str,
    lineage: str,
) -> pd.DataFrame:
    """Return singleton cluster assignments for every sequence and resolution."""
    rows = [
        {
            "sequence_id": sid,
            "window_id": window_id,
            "resolution": res,
            "cluster_id": f"{window_id}|{lineage}|R{res}|S{i}",
        }
        for i, sid in enumerate(sorted(seq_ids), start=1)
        for res in resolutions
    ]
    return pd.DataFrame(rows)


def set_igraph_seed(seed: int) -> None:
    """Set igraph's random generator when supported by the installed version."""
    try:
        ig.set_random_number_generator(np.random.default_rng(seed))
    except (AttributeError, TypeError):
        try:
            ig.set_random_number_generator(np.random.RandomState(seed))
        except Exception:
            pass


def load_pairwise_table(
    pairwise_file: Path,
    min_weight: float | None = None,
) -> pd.DataFrame:
    """Load and normalise pairwise endpoints plus compatibility weights."""
    required = ["id1", "id2", "epilink_compatibility"]
    read_kwargs: dict[str, Any] = {"columns": required}
    if min_weight is not None:
        read_kwargs["filters"] = [("epilink_compatibility", ">", float(min_weight))]
    try:
        df = pd.read_parquet(pairwise_file, **read_kwargs)
    except Exception as exc:
        raise ValueError(
            f"{pairwise_file} must contain columns: {', '.join(required)}"
        ) from exc

    df = df.rename(columns={"epilink_compatibility": "weight"})
    df = df.dropna(subset=["id1", "id2", "weight"]).copy()
    df["id1"] = df["id1"].astype(str)
    df["id2"] = df["id2"].astype(str)
    df["weight"] = pd.to_numeric(df["weight"], errors="coerce")
    df = df.dropna(subset=["weight"])
    df = df[df["id1"] != df["id2"]]

    if df.empty:
        return df

    a = np.minimum(df["id1"], df["id2"])
    b = np.maximum(df["id1"], df["id2"])
    key = pd.DataFrame({"a": a, "b": b})
    return df.loc[~key.duplicated(keep="first")].copy()


def infer_group_ids(df: pd.DataFrame) -> list[str]:
    """Infer group membership from pairwise endpoints."""
    if df.empty:
        return []
    return (
        pd.unique(pd.concat([df["id1"], df["id2"]], ignore_index=True))
        .astype(str)
        .tolist()
    )


def process_pairwise(
    pairwise_file: Path,
    out_long_dir: Path,
    resolutions: list[float],
    *,
    seq_ids_path: Path | None = None,
    seed: int = 42,
    sparsification: float = 1e-3,
) -> Path:
    """Convert one scored pairwise parquet file into Leiden cluster assignments."""
    out_long_dir.mkdir(parents=True, exist_ok=True)
    stem = pairwise_file.stem
    window_id, lineage, expected_sequences = parse_pairwise_label(stem)
    out_path = out_long_dir / f"{stem}.parquet"

    if seq_ids_path is not None and seq_ids_path.exists():
        group_ids = read_seq_ids(seq_ids_path)
        df = load_pairwise_table(
            pairwise_file,
            min_weight=sparsification,
        )
    else:
        if seq_ids_path is not None:
            logging.warning(
                "%s: seq-id file not found at %s; inferring nodes from pairwise "
                "endpoints",
                stem,
                seq_ids_path,
            )
        df = load_pairwise_table(pairwise_file)
        group_ids = infer_group_ids(df)
        if expected_sequences is not None and len(group_ids) < expected_sequences:
            logging.warning(
                "%s: inferred %d/%d nodes from pairwise endpoints; pass --seq-ids "
                "to preserve endpoint-free isolates",
                stem,
                len(group_ids),
                expected_sequences,
            )

    if not group_ids and df.empty:
        raise ValueError(
            f"{pairwise_file} has no usable rows and no --seq-ids file was provided"
        )

    if seq_ids_path is None or not seq_ids_path.exists():
        df = df[df["weight"] > sparsification]
    if df.empty:
        logging.warning("%s: all weights <= %g; writing isolates", stem, sparsification)
        result = fallback_isolates(group_ids, resolutions, window_id, lineage)
        result.to_parquet(out_path, index=False, compression="zstd")
        return out_path

    g = ig.Graph.TupleList(
        df[["id1", "id2", "weight"]].itertuples(index=False, name=None),
        directed=False,
        edge_attrs=["weight"],
    )
    missing_nodes = sorted(set(group_ids) - set(g.vs["name"]))
    if missing_nodes:
        g.add_vertices(missing_nodes)

    set_igraph_seed(seed)

    rows = []
    for res in resolutions:
        comms = g.community_leiden(weights="weight", resolution=res, n_iterations=10)
        for i, community in enumerate(comms, start=1):
            cid = f"C{i}" if len(community) > 1 else f"S{i}"
            for v_idx in community:
                rows.append(
                    {
                        "sequence_id": g.vs[v_idx]["name"],
                        "window_id": window_id,
                        "resolution": res,
                        "cluster_id": f"{window_id}|{lineage}|R{res}|{cid}",
                    }
                )

    result = pd.DataFrame(rows).sort_values(
        ["sequence_id", "resolution", "cluster_id"], kind="mergesort"
    )
    result.to_parquet(out_path, index=False, compression="zstd")
    logging.info(
        "%s: %d sequences x %d resolutions -> %s",
        stem,
        result["sequence_id"].nunique(),
        len(resolutions),
        out_path.name,
    )
    return out_path


def main() -> int:
    """Parse CLI arguments and process one scored pairwise file."""
    ap = argparse.ArgumentParser(
        description="Process one pairwise compatibility parquet into Leiden clusters."
    )
    ap.add_argument("--pairwise-file", type=Path, required=True)
    ap.add_argument(
        "--seq-ids",
        type=Path,
        default=None,
        help="Optional .ids file with full group membership.",
    )
    ap.add_argument("--out-long-dir", type=Path, required=True)
    ap.add_argument(
        "--resolutions",
        type=str,
        default="0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8",
    )
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--sparsification", type=float, default=1e-3)
    ap.add_argument("--log-level", default="INFO")

    args = ap.parse_args()

    setup_logging(args.log_level)
    resolutions = [float(x) for x in args.resolutions.split(",") if x.strip()]

    process_pairwise(
        pairwise_file=args.pairwise_file,
        out_long_dir=args.out_long_dir,
        resolutions=resolutions,
        seq_ids_path=args.seq_ids,
        seed=args.seed,
        sparsification=args.sparsification,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
