"""Public helpers for the SSE detection workflow."""

from .sse.entropy import (
    MIXING_TERTILE_FEATURES,
    MIXING_TERTILE_ORDER,
    DEFAULT_MIXING_FEATURES,
    OBSERVED_MIXING_FEATURES_X10,
    add_observed_mixing_entropy_scales,
    add_mixing_tertiles,
    cluster_socio_demo_entropy,
    observed_mixing_entropy_scales,
    onward_edge_entropy,
)
from .sse.io import HIGH_PRIORITY_CANDIDATE_TIERS, SseOutputs, load_sse_outputs

from .model.prep import (
    CLUSTER_ID_COL,
    COMPOSITION_FEATURES,
    COMPOSITION_SPECS,
    EPIDEMIC_CONTEXT_ADJUSTERS,
    GROUP_VARS,
    NULL_MIXING_FEATURES,
    OBSERVED_MIXING_FEATURES,
    SCORE_OUTCOMES,
    Domain,
    ModelSpec,
    PreparedModelFrame,
    PreparedRegressionRun,
    RegressionDataBundle,
    RegressionFamily,
    SampleSpec,
    add_standardised_adjusters,
    compact_categorical_levels,
    default_model_specs,
    default_result_dir,
    formula_with_varying_intercepts,
    get_complete_case_data,
    make_model_fit_data,
    model_output_dir,
    model_output_files,
    prepare_regression_data,
    prepare_regression_run,
    required_regression_cluster_columns,
    sample_binary_outcome_data,
    sample_rows_preserving_categories,
    treatment_term,
    validate_regression_cluster_columns,
    write_fit_frames,
    write_prepared_run_tables,
)
from .model.bayesian import (
    BayesianFitConfig,
    BayesianModelResult,
    available_posterior_vars,
    fit_and_summarise_model,
    fit_bayesian_model,
    fit_prepared_model,
    fit_prepared_run,
    has_categorical_formula_terms,
    model_diagnostics,
    posterior_dataset,
    posterior_probability_summary,
    posterior_vars_from_formula,
    print_diagnostic_report,
    random_effect_groups,
    random_effect_sigma_vars_from_formula,
    response_from_formula,
    save_model_result,
    save_prepared_model_result,
    save_prepared_run_results,
    split_formula_terms,
    summarise_bambi_idata,
    write_summary_table,
)
from .model.runner import (
    RegressionCliConfig,
    available_model_sets,
    build_domain_arg_parser,
    default_regression_result_dir,
    find_project_root,
    fit_save_and_log_frame,
    frame_key,
    load_regression_data,
    main_for_domain,
    model_log_path,
    model_outputs_exist,
    outcomes_for_family,
    prepare_domain_regression_run,
    print_available_models,
    redirect_model_output,
    resolve_model_sets,
    run_domain_models,
    sample_for_domain,
    write_model_log_header,
    write_saved_model_manifest,
)

from .sse.cluster_features import (
    build_cluster_attributes,
    build_cluster_stats,
    build_cluster_table,
)
from .sse.scoring import (
    add_composite_null_scores,
    add_sse_node_metrics,
    choose_permutation_strata,
)
from .forest import (
    ForestPlotResult,
    plot_composition_primary_expanded_forest,
    plot_logistic_composition_primary_expanded_forest,
    plot_mixing_primary_expanded_forest,
)


def __getattr__(name: str):
    """Load pipeline entry-point helpers without pre-importing executable modules."""
    if name == "load_sequence_data":
        from .sse.detection import load_sequence_data

        return load_sequence_data
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "HIGH_PRIORITY_CANDIDATE_TIERS",
    "MIXING_TERTILE_FEATURES",
    "DEFAULT_MIXING_FEATURES",
    "MIXING_TERTILE_ORDER",
    "add_observed_mixing_entropy_scales",
    "OBSERVED_MIXING_FEATURES_X10",
    "SseOutputs",
    "add_mixing_tertiles",
    "cluster_socio_demo_entropy",
    "load_sse_outputs",
    "observed_mixing_entropy_scales",
    "onward_edge_entropy",
    "load_sequence_data",
    "add_composite_null_scores",
    "add_sse_node_metrics",
    "build_cluster_attributes",
    "build_cluster_stats",
    "build_cluster_table",
    "choose_permutation_strata",
    "CLUSTER_ID_COL",
    "COMPOSITION_FEATURES",
    "COMPOSITION_SPECS",
    "EPIDEMIC_CONTEXT_ADJUSTERS",
    "GROUP_VARS",
    "NULL_MIXING_FEATURES",
    "OBSERVED_MIXING_FEATURES",
    "SCORE_OUTCOMES",
    "Domain",
    "ModelSpec",
    "PreparedModelFrame",
    "PreparedRegressionRun",
    "RegressionDataBundle",
    "RegressionFamily",
    "SampleSpec",
    "add_standardised_adjusters",
    "compact_categorical_levels",
    "default_model_specs",
    "default_result_dir",
    "formula_with_varying_intercepts",
    "get_complete_case_data",
    "make_model_fit_data",
    "model_output_dir",
    "model_output_files",
    "prepare_regression_data",
    "prepare_regression_run",
    "required_regression_cluster_columns",
    "sample_binary_outcome_data",
    "sample_rows_preserving_categories",
    "treatment_term",
    "validate_regression_cluster_columns",
    "write_fit_frames",
    "write_prepared_run_tables",
    "BayesianFitConfig",
    "BayesianModelResult",
    "available_posterior_vars",
    "fit_and_summarise_model",
    "fit_bayesian_model",
    "fit_prepared_model",
    "fit_prepared_run",
    "has_categorical_formula_terms",
    "model_diagnostics",
    "posterior_dataset",
    "posterior_probability_summary",
    "posterior_vars_from_formula",
    "print_diagnostic_report",
    "random_effect_groups",
    "random_effect_sigma_vars_from_formula",
    "response_from_formula",
    "save_model_result",
    "save_prepared_model_result",
    "save_prepared_run_results",
    "split_formula_terms",
    "summarise_bambi_idata",
    "write_summary_table",
    "RegressionCliConfig",
    "available_model_sets",
    "build_domain_arg_parser",
    "default_regression_result_dir",
    "find_project_root",
    "fit_save_and_log_frame",
    "frame_key",
    "load_regression_data",
    "main_for_domain",
    "model_log_path",
    "model_outputs_exist",
    "outcomes_for_family",
    "prepare_domain_regression_run",
    "print_available_models",
    "redirect_model_output",
    "resolve_model_sets",
    "run_domain_models",
    "sample_for_domain",
    "write_model_log_header",
    "write_saved_model_manifest",
    "plot_composition_primary_expanded_forest",
    "plot_logistic_composition_primary_expanded_forest",
    "plot_mixing_primary_expanded_forest",
    "ForestPlotResult",
]
